name: Run spectral on api description push

on:
  push:
    paths:
    - 'openapi/v1/print-trail-channel-api.yaml'
  workflow_dispatch:
  pull_request:

jobs:
  build:
    name: Run Spectral
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v2

      # Run Spectral
      - uses: stoplightio/spectral-action@v0.5.5
        with:
          file_glob: 'openapi/v1/print-trail-channel-api.yaml'
          repo_token: ${{ secrets.GITHUB_TOKEN }}
