- name: Spectral Linting
  # You may pin to the exact commit or the version.
  # uses: stoplightio/spectral-action@8ff2d4abeb218206e983b59fdbb173e5df091020
  uses: stoplightio/spectral-action@v0.7.3
  with:
    # The pattern describing the file paths to lint with Spectral
    file_glob: openapi/v1/print-trail-channel-api.yaml
    # Custom ruleset to load in Spectral.

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

